//
//  Archive.swift
//  WellWin
//
//  Created by Ivan Dudarev on 7/14/21.
//

import Foundation

public struct Archive: Codable {
   
   public var country: String?
   public var league: String?
   public var bookmaker: String?
   public var season: String?
   public var championship: String?
   public var data: [String]?
   public var time: [String]?
   public var ht: [String]?
   public var at: [String]?
   public var referee: [String]?
   public var round: [String]?
   public var htGoalsCount1half: [Int]?
   public var atGoalsCount1half: [Int]?
   public var win1half: [String]?
   public var htGoalsCount2half: [Int]?
   public var atGoalsCount2half: [Int]?
   public var win2half: [String]?
   public var htGoalsCountFt: [Int]?
   public var atGoalsCountFt: [Int]?
   public var winFt: [String]?
   public var htGoalsTime: [[Int]]?
   public var atGoalsTime: [[Int]]?
   public var ht1x2FtOpening: [Double]?
   public var ht1x2FtClosing: [Double]?
   public var d1x2FtOpening: [Double]?
   public var d1x2FtClosing: [Double]?
   public var at1x2FtOpening: [Double]?
   public var at1x2FtClosing: [Double]?
   public var ht1x21halfOpening: [Double]?
   public var ht1x21halfClosing: [Double]?
   public var d1x21halfOpening: [Double]?
   public var d1x21halfClosing: [Double]?
   public var at1x21halfOpening: [Double]?
   public var at1x21halfClosing: [Double]?
   public var ht1x22halfOpening: [Double]?
   public var ht1x22halfClosing: [Double]?
   public var d1x22halfOpening: [Double]?
   public var d1x22halfClosing: [Double]?
   public var at1x22halfOpening: [Double]?
   public var at1x22halfClosing: [Double]?
   public var htHaFtOpening: [Double]?
   public var htHaFtClosing: [Double]?
   public var atHaFtOpening: [Double]?
   public var atHaFtClosing: [Double]?
   public var htHa1halfOpening: [Double]?
   public var htHa1halfClosing: [Double]?
   public var atHa1halfOpening: [Double]?
   public var atHa1halfClosing: [Double]?
   public var htHa2halfOpening: [Double]?
   public var htHa2halfClosing: [Double]?
   public var atHa2halfOpening: [Double]?
   public var atHa2halfClosing: [Double]?
   public var over05FtOpening: [Double]?
   public var over05FtClosing: [Double]?
   public var under05FtOpening: [Double]?
   public var under05FtClosing: [Double]?
   public var over1FtOpening: [Double]?
   public var over1FtClosing: [Double]?
   public var under1FtOpening: [Double]?
   public var under1FtClosing: [Double]?
   public var over15FtOpening: [Double]?
   public var over15FtClosing: [Double]?
   public var under15FtOpening: [Double]?
   public var under15FtClosing: [Double]?
   public var over2FtOpening: [Double]?
   public var over2FtClosing: [Double]?
   public var under2FtOpening: [Double]?
   public var under2FtClosing: [Double]?
   public var over25FtOpening: [Double]?
   public var over25FtClosing: [Double]?
   public var under25FtOpening: [Double]?
   public var under25FtClosing: [Double]?
   public var over3FtOpening: [Double]?
   public var over3FtClosing: [Double]?
   public var under3FtOpening: [Double]?
   public var under3FtClosing: [Double]?
   public var over35FtOpening: [Double]?
   public var over35FtClosing: [Double]?
   public var under35FtOpening: [Double]?
   public var under35FtClosing: [Double]?
   public var over4FtOpening: [Double]?
   public var over4FtClosing: [Double]?
   public var under4FtOpening: [Double]?
   public var under4FtClosing: [Double]?
   public var over45FtOpening: [Double]?
   public var over45FtClosing: [Double]?
   public var under45FtOpening: [Double]?
   public var under45FtClosing: [Double]?
   public var over5FtOpening: [Double]?
   public var over5FtClosing: [Double]?
   public var under5FtOpening: [Double]?
   public var under5FtClosing: [Double]?
   public var over55FtOpening: [Double]?
   public var over55FtClosing: [Double]?
   public var under55FtOpening: [Double]?
   public var under55FtClosing: [Double]?
   public var over051halfOpening: [Double]?
   public var over051halfClosing: [Double]?
   public var under051halfOpening: [Double]?
   public var under051halfClosing: [Double]?
   public var over11halfOpening: [Double]?
   public var over11halfClosing: [Double]?
   public var under11halfOpening: [Double]?
   public var under11halfClosing: [Double]?
   public var over151halfOpening: [Double]?
   public var over151halfClosing: [Double]?
   public var under151halfOpening: [Double]?
   public var under151halfClosing: [Double]?
   public var over21halfOpening: [Double]?
   public var over21halfClosing: [Double]?
   public var under21halfOpening: [Double]?
   public var under21halfClosing: [Double]?
   public var over251halfOpening: [Double]?
   public var over251halfClosing: [Double]?
   public var under251halfOpening: [Double]?
   public var under251halfClosing: [Double]?
   public var over31halfOpening: [Double]?
   public var over31halfClosing: [Double]?
   public var under31halfOpening: [Double]?
   public var under31halfClosing: [Double]?
   public var over351halfOpening: [Double]?
   public var over351halfClosing: [Double]?
   public var under351halfOpening: [Double]?
   public var under351halfClosing: [Double]?
   public var over41halfOpening: [Double]?
   public var over41halfClosing: [Double]?
   public var under41halfOpening: [Double]?
   public var under41halfClosing: [Double]?
   public var over451halfOpening: [Double]?
   public var over451halfClosing: [Double]?
   public var under451halfOpening: [Double]?
   public var under451halfClosing: [Double]?
   public var over51halfOpening: [Double]?
   public var over51halfClosing: [Double]?
   public var under51halfOpening: [Double]?
   public var under51halfClosing: [Double]?
   public var over551halfOpening: [Double]?
   public var over551halfClosing: [Double]?
   public var under551halfOpening: [Double]?
   public var under551halfClosing: [Double]?
   public var over052halfOpening: [Double]?
   public var over052halfClosing: [Double]?
   public var under052halfOpening: [Double]?
   public var under052halfClosing: [Double]?
   public var over12halfOpening: [Double]?
   public var over12halfClosing: [Double]?
   public var under12halfOpening: [Double]?
   public var under12halfClosing: [Double]?
   public var over152halfOpening: [Double]?
   public var over152halfClosing: [Double]?
   public var under152halfOpening: [Double]?
   public var under152halfClosing: [Double]?
   public var over22halfOpening: [Double]?
   public var over22halfClosing: [Double]?
   public var under22halfOpening: [Double]?
   public var under22halfClosing: [Double]?
   public var over252halfOpening: [Double]?
   public var over252halfClosing: [Double]?
   public var under252halfOpening: [Double]?
   public var under252halfClosing: [Double]?
   public var over32halfOpening: [Double]?
   public var over32halfClosing: [Double]?
   public var under32halfOpening: [Double]?
   public var under32halfClosing: [Double]?
   public var over352halfOpening: [Double]?
   public var over352halfClosing: [Double]?
   public var under352halfOpening: [Double]?
   public var under352halfClosing: [Double]?
   public var over42halfOpening: [Double]?
   public var over42halfClosing: [Double]?
   public var under42halfOpening: [Double]?
   public var under42halfClosing: [Double]?
   public var over452halfOpening: [Double]?
   public var over452halfClosing: [Double]?
   public var under452halfOpening: [Double]?
   public var under452halfClosing: [Double]?
   public var over52halfOpening: [Double]?
   public var over52halfClosing: [Double]?
   public var under52halfOpening: [Double]?
   public var under52halfClosing: [Double]?
   public var over552halfOpening: [Double]?
   public var over552halfClosing: [Double]?
   public var under552halfOpening: [Double]?
   public var under552halfClosing: [Double]?
   public var dc1xFtOpening: [Double]?
   public var dc1xFtClosing: [Double]?
   public var dc12FtOpening: [Double]?
   public var dc12FtClosing: [Double]?
   public var dcX2FtOpening: [Double]?
   public var dcX2FtClosing: [Double]?
   public var dc1x1halfOpening: [Double]?
   public var dc1x1halfClosing: [Double]?
   public var dc121halfOpening: [Double]?
   public var dc121halfClosing: [Double]?
   public var dcX21halfOpening: [Double]?
   public var dcX21halfClosing: [Double]?
   public var dc1x2halfOpening: [Double]?
   public var dc1x2halfClosing: [Double]?
   public var dc122halfOpening: [Double]?
   public var dc122halfClosing: [Double]?
   public var dcX22halfOpening: [Double]?
   public var dcX22halfClosing: [Double]?
   public var htft11Opening: [Double]?
   public var htft11Closing: [Double]?
   public var htft1XOpening: [Double]?
   public var htft1XClosing: [Double]?
   public var htft12Opening: [Double]?
   public var htft12Closing: [Double]?
   public var htftX1Opening: [Double]?
   public var htftX1Closing: [Double]?
   public var htftXXOpening: [Double]?
   public var htftXXClosing: [Double]?
   public var htftX2Opening: [Double]?
   public var htftX2Closing: [Double]?
   public var htft21Opening: [Double]?
   public var htft21Closing: [Double]?
   public var htft2XOpening: [Double]?
   public var htft2XClosing: [Double]?
   public var htft22Opening: [Double]?
   public var htft22Closing: [Double]?
   public var cs66Opening: [Double]?
   public var cs66Closing: [Double]?
   public var cs65Opening: [Double]?
   public var cs65Closing: [Double]?
   public var cs64Opening: [Double]?
   public var cs64Closing: [Double]?
   public var cs63Opening: [Double]?
   public var cs63Closing: [Double]?
   public var cs62Opening: [Double]?
   public var cs62Closing: [Double]?
   public var cs61Opening: [Double]?
   public var cs61Closing: [Double]?
   public var cs60Opening: [Double]?
   public var cs60Closing: [Double]?
   public var cs56Opening: [Double]?
   public var cs56Closing: [Double]?
   public var cs55Opening: [Double]?
   public var cs55Closing: [Double]?
   public var cs54Opening: [Double]?
   public var cs54Closing: [Double]?
   public var cs53Opening: [Double]?
   public var cs53Closing: [Double]?
   public var cs52Opening: [Double]?
   public var cs52Closing: [Double]?
   public var cs51Opening: [Double]?
   public var cs51Closing: [Double]?
   public var cs50Opening: [Double]?
   public var cs50Closing: [Double]?
   public var cs46Opening: [Double]?
   public var cs46Closing: [Double]?
   public var cs45Opening: [Double]?
   public var cs45Closing: [Double]?
   public var cs44Opening: [Double]?
   public var cs44Closing: [Double]?
   public var cs43Opening: [Double]?
   public var cs43Closing: [Double]?
   public var cs42Opening: [Double]?
   public var cs42Closing: [Double]?
   public var cs41Opening: [Double]?
   public var cs41Closing: [Double]?
   public var cs40Opening: [Double]?
   public var cs40Closing: [Double]?
   public var cs36Opening: [Double]?
   public var cs36Closing: [Double]?
   public var cs35Opening: [Double]?
   public var cs35Closing: [Double]?
   public var cs34Opening: [Double]?
   public var cs34Closing: [Double]?
   public var cs33Opening: [Double]?
   public var cs33Closing: [Double]?
   public var cs32Opening: [Double]?
   public var cs32Closing: [Double]?
   public var cs31Opening: [Double]?
   public var cs31Closing: [Double]?
   public var cs30Opening: [Double]?
   public var cs30Closing: [Double]?
   public var cs26Opening: [Double]?
   public var cs26Closing: [Double]?
   public var cs25Opening: [Double]?
   public var cs25Closing: [Double]?
   public var cs24Opening: [Double]?
   public var cs24Closing: [Double]?
   public var cs23Opening: [Double]?
   public var cs23Closing: [Double]?
   public var cs22Opening: [Double]?
   public var cs22Closing: [Double]?
   public var cs21Opening: [Double]?
   public var cs21Closing: [Double]?
   public var cs20Opening: [Double]?
   public var cs20Closing: [Double]?
   public var cs16Opening: [Double]?
   public var cs16Closing: [Double]?
   public var cs15Opening: [Double]?
   public var cs15Closing: [Double]?
   public var cs14Opening: [Double]?
   public var cs14Closing: [Double]?
   public var cs13Opening: [Double]?
   public var cs13Closing: [Double]?
   public var cs12Opening: [Double]?
   public var cs12Closing: [Double]?
   public var cs11Opening: [Double]?
   public var cs11Closing: [Double]?
   public var cs10Opening: [Double]?
   public var cs10Closing: [Double]?
   public var cs00Opening: [Double]?
   public var cs00Closing: [Double]?
   public var cs06Opening: [Double]?
   public var cs06Closing: [Double]?
   public var cs05Opening: [Double]?
   public var cs05Closing: [Double]?
   public var cs04Opening: [Double]?
   public var cs04Closing: [Double]?
   public var cs03Opening: [Double]?
   public var cs03Closing: [Double]?
   public var cs02Opening: [Double]?
   public var cs02Closing: [Double]?
   public var cs01Opening: [Double]?
   public var cs01Closing: [Double]?
   public var oddFtOpening: [Double]?
   public var oddFtClosing: [Double]?
   public var evenFtOpening: [Double]?
   public var evenFtClosing: [Double]?
   public var odd1halfOpening: [Double]?
   public var odd1halfClosing: [Double]?
   public var even1halfOpening: [Double]?
   public var even1halfClosing: [Double]?
   public var odd2halfOpening: [Double]?
   public var odd2halfClosing: [Double]?
   public var even2halfOpening: [Double]?
   public var even2halfClosing: [Double]?
   public var btsYesFtOpening: [Double]?
   public var btsYesFtClosing: [Double]?
   public var btsNoFtOpening: [Double]?
   public var btsNoFtClosing: [Double]?
   public var btsYes1halfOpening: [Double]?
   public var btsYes1halfClosing: [Double]?
   public var btsNo1halfOpening: [Double]?
   public var btsNo1halfClosing: [Double]?
   public var btsYes2halfOpening: [Double]?
   public var btsYes2halfClosing: [Double]?
   public var btsNo2halfOpening: [Double]?
   public var btsNo2halfClosing: [Double]?
   public var yellowCardHt: [Int]?
   public var yellowCardAt: [Int]?
   public var redCardHt: [Int]?
   public var redCardAt: [Int]?
   public var cornerKicksHt: [Int]?
   public var cornerKicksAt: [Int]?
   
   public init() {}
   
   public enum CodingKeys: String, CodingKey, CaseIterable {
      case country
      case league
      case bookmaker
      case season
      case championship
      case data
      case time
      case ht
      case at
      case referee
      case round
      case htGoalsCount1half = "ht_goals_count_1half"
      case atGoalsCount1half = "at_goals_count_1half"
      case win1half = "win_1half"
      case htGoalsCount2half = "ht_goals_count_2half"
      case atGoalsCount2half = "at_goals_count_2half"
      case win2half = "win_2half"
      case htGoalsCountFt = "ht_goals_count_ft"
      case atGoalsCountFt = "at_goals_count_ft"
      case winFt = "win_ft"
      case htGoalsTime = "ht_goals_time"
      case atGoalsTime = "at_goals_time"
      case ht1x2FtOpening = "ht_1x2_ft_opening"
      case ht1x2FtClosing = "ht_1x2_ft_closing"
      case d1x2FtOpening = "d_1x2_ft_opening"
      case d1x2FtClosing = "d_1x2_ft_closing"
      case at1x2FtOpening = "at_1x2_ft_opening"
      case at1x2FtClosing = "at_1x2_ft_closing"
      case ht1x21halfOpening = "ht_1x2_1half_opening"
      case ht1x21halfClosing = "ht_1x2_1half_closing"
      case d1x21halfOpening = "d_1x2_1half_opening"
      case d1x21halfClosing = "d_1x2_1half_closing"
      case at1x21halfOpening = "at_1x2_1half_opening"
      case at1x21halfClosing = "at_1x2_1half_closing"
      case ht1x22halfOpening = "ht_1x2_2half_opening"
      case ht1x22halfClosing = "ht_1x2_2half_closing"
      case d1x22halfOpening = "d_1x2_2half_opening"
      case d1x22halfClosing = "d_1x2_2half_closing"
      case at1x22halfOpening = "at_1x2_2half_opening"
      case at1x22halfClosing = "at_1x2_2half_closing"
      case htHaFtOpening = "ht_ha_ft_opening"
      case htHaFtClosing = "ht_ha_ft_closing"
      case atHaFtOpening = "at_ha_ft_opening"
      case atHaFtClosing = "at_ha_ft_closing"
      case htHa1halfOpening = "ht_ha_1half_opening"
      case htHa1halfClosing = "ht_ha_1half_closing"
      case atHa1halfOpening = "at_ha_1half_opening"
      case atHa1halfClosing = "at_ha_1half_closing"
      case htHa2halfOpening = "ht_ha_2half_opening"
      case htHa2halfClosing = "ht_ha_2half_closing"
      case atHa2halfOpening = "at_ha_2half_opening"
      case atHa2halfClosing = "at_ha_2half_closing"
      case over05FtOpening = "over_0_5_ft_opening"
      case over05FtClosing = "over_0_5_ft_closing"
      case under05FtOpening = "under_0_5_ft_opening"
      case under05FtClosing = "under_0_5_ft_closing"
      case over1FtOpening = "over_1_ft_opening"
      case over1FtClosing = "over_1_ft_closing"
      case under1FtOpening = "under_1_ft_opening"
      case under1FtClosing = "under_1_ft_closing"
      case over15FtOpening = "over_1_5_ft_opening"
      case over15FtClosing = "over_1_5_ft_closing"
      case under15FtOpening = "under_1_5_ft_opening"
      case under15FtClosing = "under_1_5_ft_closing"
      case over2FtOpening = "over_2_ft_opening"
      case over2FtClosing = "over_2_ft_closing"
      case under2FtOpening = "under_2_ft_opening"
      case under2FtClosing = "under_2_ft_closing"
      case over25FtOpening = "over_2_5_ft_opening"
      case over25FtClosing = "over_2_5_ft_closing"
      case under25FtOpening = "under_2_5_ft_opening"
      case under25FtClosing = "under_2_5_ft_closing"
      case over3FtOpening = "over_3_ft_opening"
      case over3FtClosing = "over_3_ft_closing"
      case under3FtOpening = "under_3_ft_opening"
      case under3FtClosing = "under_3_ft_closing"
      case over35FtOpening = "over_3_5_ft_opening"
      case over35FtClosing = "over_3_5_ft_closing"
      case under35FtOpening = "under_3_5_ft_opening"
      case under35FtClosing = "under_3_5_ft_closing"
      case over4FtOpening = "over_4_ft_opening"
      case over4FtClosing = "over_4_ft_closing"
      case under4FtOpening = "under_4_ft_opening"
      case under4FtClosing = "under_4_ft_closing"
      case over45FtOpening = "over_4_5_ft_opening"
      case over45FtClosing = "over_4_5_ft_closing"
      case under45FtOpening = "under_4_5_ft_opening"
      case under45FtClosing = "under_4_5_ft_closing"
      case over5FtOpening = "over_5_ft_opening"
      case over5FtClosing = "over_5_ft_closing"
      case under5FtOpening = "under_5_ft_opening"
      case under5FtClosing = "under_5_ft_closing"
      case over55FtOpening = "over_5_5_ft_opening"
      case over55FtClosing = "over_5_5_ft_closing"
      case under55FtOpening = "under_5_5_ft_opening"
      case under55FtClosing = "under_5_5_ft_closing"
      case over051halfOpening = "over_0_5_1half_opening"
      case over051halfClosing = "over_0_5_1half_closing"
      case under051halfOpening = "under_0_5_1half_opening"
      case under051halfClosing = "under_0_5_1half_closing"
      case over11halfOpening = "over_1_1half_opening"
      case over11halfClosing = "over_1_1half_closing"
      case under11halfOpening = "under_1_1half_opening"
      case under11halfClosing = "under_1_1half_closing"
      case over151halfOpening = "over_1_5_1half_opening"
      case over151halfClosing = "over_1_5_1half_closing"
      case under151halfOpening = "under_1_5_1half_opening"
      case under151halfClosing = "under_1_5_1half_closing"
      case over21halfOpening = "over_2_1half_opening"
      case over21halfClosing = "over_2_1half_closing"
      case under21halfOpening = "under_2_1half_opening"
      case under21halfClosing = "under_2_1half_closing"
      case over251halfOpening = "over_2_5_1half_opening"
      case over251halfClosing = "over_2_5_1half_closing"
      case under251halfOpening = "under_2_5_1half_opening"
      case under251halfClosing = "under_2_5_1half_closing"
      case over31halfOpening = "over_3_1half_opening"
      case over31halfClosing = "over_3_1half_closing"
      case under31halfOpening = "under_3_1half_opening"
      case under31halfClosing = "under_3_1half_closing"
      case over351halfOpening = "over_3_5_1half_opening"
      case over351halfClosing = "over_3_5_1half_closing"
      case under351halfOpening = "under_3_5_1half_opening"
      case under351halfClosing = "under_3_5_1half_closing"
      case over41halfOpening = "over_4_1half_opening"
      case over41halfClosing = "over_4_1half_closing"
      case under41halfOpening = "under_4_1half_opening"
      case under41halfClosing = "under_4_1half_closing"
      case over451halfOpening = "over_4_5_1half_opening"
      case over451halfClosing = "over_4_5_1half_closing"
      case under451halfOpening = "under_4_5_1half_opening"
      case under451halfClosing = "under_4_5_1half_closing"
      case over51halfOpening = "over_5_1half_opening"
      case over51halfClosing = "over_5_1half_closing"
      case under51halfOpening = "under_5_1half_opening"
      case under51halfClosing = "under_5_1half_closing"
      case over551halfOpening = "over_5_5_1half_opening"
      case over551halfClosing = "over_5_5_1half_closing"
      case under551halfOpening = "under_5_5_1half_opening"
      case under551halfClosing = "under_5_5_1half_closing"
      case over052halfOpening = "over_0_5_2half_opening"
      case over052halfClosing = "over_0_5_2half_closing"
      case under052halfOpening = "under_0_5_2half_opening"
      case under052halfClosing = "under_0_5_2half_closing"
      case over12halfOpening = "over_1_2half_opening"
      case over12halfClosing = "over_1_2half_closing"
      case under12halfOpening = "under_1_2half_opening"
      case under12halfClosing = "under_1_2half_closing"
      case over152halfOpening = "over_1_5_2half_opening"
      case over152halfClosing = "over_1_5_2half_closing"
      case under152halfOpening = "under_1_5_2half_opening"
      case under152halfClosing = "under_1_5_2half_closing"
      case over22halfOpening = "over_2_2half_opening"
      case over22halfClosing = "over_2_2half_closing"
      case under22halfOpening = "under_2_2half_opening"
      case under22halfClosing = "under_2_2half_closing"
      case over252halfOpening = "over_2_5_2half_opening"
      case over252halfClosing = "over_2_5_2half_closing"
      case under252halfOpening = "under_2_5_2half_opening"
      case under252halfClosing = "under_2_5_2half_closing"
      case over32halfOpening = "over_3_2half_opening"
      case over32halfClosing = "over_3_2half_closing"
      case under32halfOpening = "under_3_2half_opening"
      case under32halfClosing = "under_3_2half_closing"
      case over352halfOpening = "over_3_5_2half_opening"
      case over352halfClosing = "over_3_5_2half_closing"
      case under352halfOpening = "under_3_5_2half_opening"
      case under352halfClosing = "under_3_5_2half_closing"
      case over42halfOpening = "over_4_2half_opening"
      case over42halfClosing = "over_4_2half_closing"
      case under42halfOpening = "under_4_2half_opening"
      case under42halfClosing = "under_4_2half_closing"
      case over452halfOpening = "over_4_5_2half_opening"
      case over452halfClosing = "over_4_5_2half_closing"
      case under452halfOpening = "under_4_5_2half_opening"
      case under452halfClosing = "under_4_5_2half_closing"
      case over52halfOpening = "over_5_2half_opening"
      case over52halfClosing = "over_5_2half_closing"
      case under52halfOpening = "under_5_2half_opening"
      case under52halfClosing = "under_5_2half_closing"
      case over552halfOpening = "over_5_5_2half_opening"
      case over552halfClosing = "over_5_5_2half_closing"
      case under552halfOpening = "under_5_5_2half_opening"
      case under552halfClosing = "under_5_5_2half_closing"
      case dc1xFtOpening = "dc_1x_ft_opening"
      case dc1xFtClosing = "dc_1x_ft_closing"
      case dc12FtOpening = "dc_12_ft_opening"
      case dc12FtClosing = "dc_12_ft_closing"
      case dcX2FtOpening = "dc_x2_ft_opening"
      case dcX2FtClosing = "dc_x2_ft_closing"
      case dc1x1halfOpening = "dc_1x_1half_opening"
      case dc1x1halfClosing = "dc_1x_1half_closing"
      case dc121halfOpening = "dc_12_1half_opening"
      case dc121halfClosing = "dc_12_1half_closing"
      case dcX21halfOpening = "dc_x2_1half_opening"
      case dcX21halfClosing = "dc_x2_1half_closing"
      case dc1x2halfOpening = "dc_1x_2half_opening"
      case dc1x2halfClosing = "dc_1x_2half_closing"
      case dc122halfOpening = "dc_12_2half_opening"
      case dc122halfClosing = "dc_12_2half_closing"
      case dcX22halfOpening = "dc_x2_2half_opening"
      case dcX22halfClosing = "dc_x2_2half_closing"
      case htft11Opening = "htft_1_1_opening"
      case htft11Closing = "htft_1_1_closing"
      case htft1XOpening = "htft_1_x_opening"
      case htft1XClosing = "htft_1_x_closing"
      case htft12Opening = "htft_1_2_opening"
      case htft12Closing = "htft_1_2_closing"
      case htftX1Opening = "htft_x_1_opening"
      case htftX1Closing = "htft_x_1_closing"
      case htftXXOpening = "htft_x_x_opening"
      case htftXXClosing = "htft_x_x_closing"
      case htftX2Opening = "htft_x_2_opening"
      case htftX2Closing = "htft_x_2_closing"
      case htft21Opening = "htft_2_1_opening"
      case htft21Closing = "htft_2_1_closing"
      case htft2XOpening = "htft_2_x_opening"
      case htft2XClosing = "htft_2_x_closing"
      case htft22Opening = "htft_2_2_opening"
      case htft22Closing = "htft_2_2_closing"
      case cs66Opening = "cs_6_6_opening"
      case cs66Closing = "cs_6_6_closing"
      case cs65Opening = "cs_6_5_opening"
      case cs65Closing = "cs_6_5_closing"
      case cs64Opening = "cs_6_4_opening"
      case cs64Closing = "cs_6_4_closing"
      case cs63Opening = "cs_6_3_opening"
      case cs63Closing = "cs_6_3_closing"
      case cs62Opening = "cs_6_2_opening"
      case cs62Closing = "cs_6_2_closing"
      case cs61Opening = "cs_6_1_opening"
      case cs61Closing = "cs_6_1_closing"
      case cs60Opening = "cs_6_0_opening"
      case cs60Closing = "cs_6_0_closing"
      case cs56Opening = "cs_5_6_opening"
      case cs56Closing = "cs_5_6_closing"
      case cs55Opening = "cs_5_5_opening"
      case cs55Closing = "cs_5_5_closing"
      case cs54Opening = "cs_5_4_opening"
      case cs54Closing = "cs_5_4_closing"
      case cs53Opening = "cs_5_3_opening"
      case cs53Closing = "cs_5_3_closing"
      case cs52Opening = "cs_5_2_opening"
      case cs52Closing = "cs_5_2_closing"
      case cs51Opening = "cs_5_1_opening"
      case cs51Closing = "cs_5_1_closing"
      case cs50Opening = "cs_5_0_opening"
      case cs50Closing = "cs_5_0_closing"
      case cs46Opening = "cs_4_6_opening"
      case cs46Closing = "cs_4_6_closing"
      case cs45Opening = "cs_4_5_opening"
      case cs45Closing = "cs_4_5_closing"
      case cs44Opening = "cs_4_4_opening"
      case cs44Closing = "cs_4_4_closing"
      case cs43Opening = "cs_4_3_opening"
      case cs43Closing = "cs_4_3_closing"
      case cs42Opening = "cs_4_2_opening"
      case cs42Closing = "cs_4_2_closing"
      case cs41Opening = "cs_4_1_opening"
      case cs41Closing = "cs_4_1_closing"
      case cs40Opening = "cs_4_0_opening"
      case cs40Closing = "cs_4_0_closing"
      case cs36Opening = "cs_3_6_opening"
      case cs36Closing = "cs_3_6_closing"
      case cs35Opening = "cs_3_5_opening"
      case cs35Closing = "cs_3_5_closing"
      case cs34Opening = "cs_3_4_opening"
      case cs34Closing = "cs_3_4_closing"
      case cs33Opening = "cs_3_3_opening"
      case cs33Closing = "cs_3_3_closing"
      case cs32Opening = "cs_3_2_opening"
      case cs32Closing = "cs_3_2_closing"
      case cs31Opening = "cs_3_1_opening"
      case cs31Closing = "cs_3_1_closing"
      case cs30Opening = "cs_3_0_opening"
      case cs30Closing = "cs_3_0_closing"
      case cs26Opening = "cs_2_6_opening"
      case cs26Closing = "cs_2_6_closing"
      case cs25Opening = "cs_2_5_opening"
      case cs25Closing = "cs_2_5_closing"
      case cs24Opening = "cs_2_4_opening"
      case cs24Closing = "cs_2_4_closing"
      case cs23Opening = "cs_2_3_opening"
      case cs23Closing = "cs_2_3_closing"
      case cs22Opening = "cs_2_2_opening"
      case cs22Closing = "cs_2_2_closing"
      case cs21Opening = "cs_2_1_opening"
      case cs21Closing = "cs_2_1_closing"
      case cs20Opening = "cs_2_0_opening"
      case cs20Closing = "cs_2_0_closing"
      case cs16Opening = "cs_1_6_opening"
      case cs16Closing = "cs_1_6_closing"
      case cs15Opening = "cs_1_5_opening"
      case cs15Closing = "cs_1_5_closing"
      case cs14Opening = "cs_1_4_opening"
      case cs14Closing = "cs_1_4_closing"
      case cs13Opening = "cs_1_3_opening"
      case cs13Closing = "cs_1_3_closing"
      case cs12Opening = "cs_1_2_opening"
      case cs12Closing = "cs_1_2_closing"
      case cs11Opening = "cs_1_1_opening"
      case cs11Closing = "cs_1_1_closing"
      case cs10Opening = "cs_1_0_opening"
      case cs10Closing = "cs_1_0_closing"
      case cs00Opening = "cs_0_0_opening"
      case cs00Closing = "cs_0_0_closing"
      case cs06Opening = "cs_0_6_opening"
      case cs06Closing = "cs_0_6_closing"
      case cs05Opening = "cs_0_5_opening"
      case cs05Closing = "cs_0_5_closing"
      case cs04Opening = "cs_0_4_opening"
      case cs04Closing = "cs_0_4_closing"
      case cs03Opening = "cs_0_3_opening"
      case cs03Closing = "cs_0_3_closing"
      case cs02Opening = "cs_0_2_opening"
      case cs02Closing = "cs_0_2_closing"
      case cs01Opening = "cs_0_1_opening"
      case cs01Closing = "cs_0_1_closing"
      case oddFtOpening = "odd_ft_opening"
      case oddFtClosing = "odd_ft_closing"
      case evenFtOpening = "even_ft_opening"
      case evenFtClosing = "even_ft_closing"
      case odd1halfOpening = "odd_1half_opening"
      case odd1halfClosing = "odd_1half_closing"
      case even1halfOpening = "even_1half_opening"
      case even1halfClosing = "even_1half_closing"
      case odd2halfOpening = "odd_2half_opening"
      case odd2halfClosing = "odd_2half_closing"
      case even2halfOpening = "even_2half_opening"
      case even2halfClosing = "even_2half_closing"
      case btsYesFtOpening = "bts_yes_ft_opening"
      case btsYesFtClosing = "bts_yes_ft_closing"
      case btsNoFtOpening = "bts_no_ft_opening"
      case btsNoFtClosing = "bts_no_ft_closing"
      case btsYes1halfOpening = "bts_yes_1half_opening"
      case btsYes1halfClosing = "bts_yes_1half_closing"
      case btsNo1halfOpening = "bts_no_1half_opening"
      case btsNo1halfClosing = "bts_no_1half_closing"
      case btsYes2halfOpening = "bts_yes_2half_opening"
      case btsYes2halfClosing = "bts_yes_2half_closing"
      case btsNo2halfOpening = "bts_no_2half_opening"
      case btsNo2halfClosing = "bts_no_2half_closing"
      case yellowCardHt = "yellow_card_ht"
      case yellowCardAt = "yellow_card_at"
      case redCardHt = "red_card_ht"
      case redCardAt = "red_card_at"
      case cornerKicksHt = "corner_kicks_ht"
      case cornerKicksAt = "corner_kicks_at"
   }
}

